server:
  port: 8080
  forward-headers-strategy: native

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/global_ship
    username: admin
    password: admin
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      validation-timeout: 5000
      keepalive-time: 60000
      max-lifetime: 1800000
      idle-timeout: 600000
      initialization-fail-timeout: -1
      connection-test-query: SELECT 1

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        default_batch_fetch_size: 1000
        query:
          plan_cache_max_size: 4096
          plan_parameter_metadata_max_size: 256

security:
  jwt:
    secret: hschurchhschurch
    access-token-ttl-seconds: 36000000000
    refresh-token-ttl-seconds: 86400000000

discord:
  error-webhook-url: https://discord.com/api/webhooks/1462367693540823197/OD3poHe0OmJyk0i0yVptQX6NwonRYRmF_rpIZa0xKgRvZIUX1u-NFLYdakWJ4-cmPP5P

youtube:
  url: https://www.googleapis.com/youtube
  x-goog-api-key: AIzaSyCCpfl0TVqidEjoExH7erRW7q-0NVHvbtQ
  channel-id: UCkIJrDEmpp4y3qGEiGyquTA
  playlist-id: PLoE5IEOib3i8lXx9J3Ce1JSlcX17Umwv_

aws:
  s3:
    bucket: hsbapch-storage
    region: ap-northeast-2
    access-key: AKIA6HW5JCWPYWBQXTOL
    secret-key: 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